Update patch set 1
Patch Set 1:

1) In the chromium DEPS file, change the SwiftShader git hash to the most recent version of SwiftShader.

2) In src/OpenGL/libEGL/BUILD.gn, remove the "} else if (is_linux) {" case that adds extra source files.

3) When building Chromium, you must use 'gn args out/Default' (assuming you are building Default) and set these flags:

#linux ubsan flags:
clang_use_chrome_plugins = false
is_clang = true
is_component_build = false
is_debug = false
is_ubsan_no_recover = true
is_ubsan_vptr = true
sanitizer_coverage_flags = "edge"

4) Run 'ninja -C out/Default swiftshader_unittests'

I get the following linking errors (which are related to having undefined virtual functions in each of these classes):
swiftshader/libEGL.so: error: undefined reference to 'typeinfo for egl::Image'
swiftshader/libEGL.so: error: undefined reference to 'typeinfo for sw::FrameBuffer'
swiftshader/libEGL.so: error: undefined reference to 'typeinfo for sw::Surface'
swiftshader/libGLESv2.so: error: undefined reference to 'typeinfo for egl::Display'
swiftshader/libGLESv2.so: error: undefined reference to 'typeinfo for egl::Surface'

Patch-set: 1