Suppress -Wunnecessary-virtual-specifier
With clang update, building code using llvm-project headers from older
version triggers the following build errors:

external/swiftshader/third_party/llvm-10.0/llvm/lib/Target/X86/X86InstrInfo.h:136:16:
 error: virtual method 'anchor' is inside a 'final' class and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
external/swiftshader/third_party/llvm-16.0/llvm/include/llvm/IR/ConstantFolder.h:31:16:
 error: virtual method 'anchor' is inside a 'final' class and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]

So suppress -Wunnecessary-virtual-specifier when llvm-project headers
are used.

Bug: 452729455
Test: build with clang update
Change-Id: Ideadeaae7bebb945bc8f87a5aed419731afc0c14
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/76828
Presubmit-Ready: Geoff Lang <geofflang@google.com>
Commit-Queue: Geoff Lang <geofflang@google.com>
Reviewed-by: Geoff Lang <geofflang@google.com>
Kokoro-Result: kokoro <noreply+kokoro@google.com>
Tested-by: Geoff Lang <geofflang@google.com>