Default to use llvm16
Fuchsia would still use llvm10 due to missing third_party/llvm-16.0/configs/fuchsia

Additional changes to llvm16 code are made to fix warnings.

Fix the following error when compiling chromium targeting riscv64 using llvm 10

../../third_party/swiftshader/src/Reactor/LLVMJIT.cpp:796:83: error: no member named 'Create' in 'llvm::jitlink::InProcessMemoryManager'
  796 |             , objectLayer(session, llvm::cantFail(llvm::jitlink::InProcessMemoryManager::Create()))
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated

Change-Id: I5aa2b77ee80cabb7ebe1641dcedea35a57b4933d
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/75929
Reviewed-by: Geoff Lang <geofflang@google.com>
Commit-Queue: Geoff Lang <geofflang@google.com>
Tested-by: Geoff Lang <geofflang@google.com>
Reviewed-by: Shahbaz Youssefi <syoussefi@google.com>
Kokoro-Result: kokoro <noreply+kokoro@google.com>