Regres: Use 'default' dEQP target and skip GLES daily tests
Using -DDEQP_TARGET=x11_egl caused a build error on some systems:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'

Using 'default' instead makes the build succeed, and makes XCB WSI tests
pass. However, GLES tests crash. Since we no longer need them due to
SwANGLE, with SwiftShader becoming Vulkan-only, this change removes them
from the test run. Also, the dEQP build is reduced to just the deqp-vk
target.

Lastly, code coverage generation on 'daily' test runs is disabled. It
produced errors such as:
Failed to process test coverage for test 'dEQP-VK.***'.
llvm-profdata errored. Cause: exit status 1

It was already disabled locally on the Regres bot to avoid these
errors.

Bug: b/189469951
Bug: b/152192800
Change-Id: I07383e1168cc322bb9247ed39db091f91c054b6d
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54589
Kokoro-Result: kokoro <noreply+kokoro@google.com>
Tested-by: Nicolas Capens <nicolascapens@google.com>
Reviewed-by: Nicolas Capens <nicolascapens@google.com>