Use aligned allocation for classes with aligned members
The legacy PixelProcessor and VertexProcessor classes for OpenGL ES
contain member fields with types like float4, which require 16-byte
alignment. This isn't guaranteed by the compiler until C++17. On macOS,
this also requires OS support, which was added in version 10.14
(Mojave), while Chrome still has to support macOS 10.11.

src/Renderer/PixelProcessor.cpp:75:18: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer

Overriding new and delete for these classes allows us to use our custom
allocator which guarantees alignment. Note that the Renderer class
already used the same approach. Also note that this hasn't caused issues
before because these fields aren't actually accessed by instructions
which demand alignment. However, it's still good for performance and to
align with the intent (pun intended).

Bug: b/174843857
Change-Id: Ia5de5f6fe67a4f54805cdde3fed565c30b9318a8
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/52029
Reviewed-by: Antonio Maiorano <amaiorano@google.com>
Tested-by: Nicolas Capens <nicolascapens@google.com>