Fix MacOS build with LLVM 16
Add missing sys/resources.h to fix Chromium build with swiftshader with
LLVM 16.

[878/74241] CXX obj/third_party/swiftshader/third_party/llvm-16.0/swiftshader_llvm_source_set_0/CrashRecoveryContext.o
../../third_party/swiftshader/third_party/llvm-16.0/llvm/lib/Support/CrashRecoveryContext.cpp:479:15: error: use of undeclared identifier 'PRIO_DARWIN_THREAD'
  479 |   setpriority(PRIO_DARWIN_THREAD, 0, PRIO_DARWIN_BG);
      |               ^~~~~~~~~~~~~~~~~~
../../third_party/swiftshader/third_party/llvm-16.0/llvm/lib/Support/CrashRecoveryContext.cpp:479:38: error: use of undeclared identifier 'PRIO_DARWIN_BG'
  479 |   setpriority(PRIO_DARWIN_THREAD, 0, PRIO_DARWIN_BG);
      |                                      ^~~~~~~~~~~~~~
../../third_party/swiftshader/third_party/llvm-16.0/llvm/lib/Support/CrashRecoveryContext.cpp:485:22: error: use of undeclared identifier 'PRIO_DARWIN_THREAD'
  485 |   return getpriority(PRIO_DARWIN_THREAD, 0) == 1;
      |                      ^~~~~~~~~~~~~~~~~~
3 errors generated.

Change-Id: Idf1d95496b1fa093c21214acbcf94fd50f3967d0
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/77308
Kokoro-Result: kokoro <noreply+kokoro@google.com>
Tested-by: Geoff Lang <geofflang@google.com>
Reviewed-by: Shahbaz Youssefi <syoussefi@google.com>
Reviewed-by: Geoff Lang <geofflang@google.com>
Commit-Queue: Geoff Lang <geofflang@google.com>