Remove two minor compiler warnings/errors:
Found when building with the Fuchsia toolchain, which
uses a recent clang version:

- The constants '1.0f / 0x7FFFFFFF' and
  '1.0f / 0xFFFFFFFF' cannot be computed directly without
  losing one bit of accuracy, and the compiler was complaining
  about it, so use intermediate double values
  to get the correct, final result.

- The MemoryMapped class needs to be declared final to
  have a final destructor, otherwise the compiler complains
  with:

    error: class with destructor marked 'final' cannot be inherited from
    [-Werror,-Wfinal-dtor-non-final-class]

Bug: None
Change-Id: I9728df87fd5d12418ef7d73aa651eca02b0e36f9
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/42888
Kokoro-Presubmit: kokoro <noreply+kokoro@google.com>
Reviewed-by: Ben Clayton <bclayton@google.com>
Tested-by: Ben Clayton <bclayton@google.com>